name: Validate Compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/AceButton
        git clone https://github.com/bxparks/AceCRC
        git clone https://github.com/bxparks/AceCommon
        git clone https://github.com/bxparks/AceRoutine
        git clone https://github.com/bxparks/AceTime
        git clone https://github.com/bxparks/AceUtils
        git clone https://github.com/bxparks/EpoxyDuino
        git clone https://github.com/greiman/SSD1306Ascii

    - name: Compile
      run: |
        make -C CommandLineClock
        make -C MedMinder
        make -C OneZoneClock
        make -C WorldClock
        make -C WorldClockLcd
