name: Validate Compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/AUnit
        git clone https://github.com/bxparks/AceButton
        git clone https://github.com/bxparks/AceCRC
        git clone https://github.com/bxparks/AceCommon
        git clone https://github.com/bxparks/AceRoutine
        git clone https://github.com/bxparks/AceSPI
        git clone https://github.com/bxparks/AceSegment
        git clone https://github.com/bxparks/AceSegmentWriter
        git clone https://github.com/bxparks/AceTMI
        git clone https://github.com/bxparks/AceTime
        git clone https://github.com/bxparks/AceUtils
        git clone https://github.com/bxparks/AceWire
        git clone https://github.com/bxparks/EpoxyDuino
        git clone https://github.com/greiman/SSD1306Ascii

    - name: Compile
      run: make all
