# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := LedClockTiny
ARDUINO_LIBS := EpoxyMockDigitalWriteFast AceCommon AceButton AceTime \
	AceRoutine AceSegment AUnit
include ../../EpoxyDuino/EpoxyDuino.mk
